### ISSUE TITLE
Abbr-tags in h1 becomes non breaking space when using horunge.js

### ISSUE THREAD

**Issue by nofont** [davidpaulsson/horunge.js#8]
I'm using the abbr-tag in my headlines to wrap and replace uppercase abbrevations with true smallcaps but the script removes them and replaces it with a non-breaking space. See screenshot.

![horunge_abbr](https://cloud.githubusercontent.com/assets/164717/6311069/b592953e-b95d-11e4-8abc-fcd7340c32f8.jpg)

**Comment by davidpaulsson** [comment]
Thanks for reporting! This should be fixed in 31b4f5dc77ceb22716c10c3a3354407a821bb01a

Please update your script to v0.0.7 using `$ bower update jquery-horunge`
